# Generated by Django 4.2.4 on 2023-09-26 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, max_length=150, null=True, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Сообщение')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время рассылки')),
                ('period', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default=('daily', 'Ежедневно'), max_length=100, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('created', 'создана'), ('launched', 'запушена'), ('finished', 'завершена')], default=('created', 'создана'), max_length=100, verbose_name='Статус')),
                ('client', models.ManyToManyField(to='mailing.client', verbose_name='Получатели')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt_time', models.DateTimeField(auto_now=True, verbose_name='время последней попытки')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failure', 'Не успешно')], max_length=50, verbose_name='статус')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_log', to='mailing.message', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'Логи рассылка',
                'verbose_name_plural': 'Логи рассылки',
            },
        ),
    ]
