# Generated by Django 4.2.4 on 2023-09-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, max_length=150, null=True, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Сообщение')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время рассылки')),
                ('period', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default=('daily', 'Ежедневно'), max_length=100, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('created', 'создана'), ('launched', 'запушена'), ('finished', 'завершена')], default=('created', 'создана'), max_length=100, verbose_name='Статус')),
                ('client', models.ManyToManyField(to='mailing.client', verbose_name='Получатели')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
