# Generated by Django 4.2.4 on 2023-09-02 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Client',
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройки'},
        ),
    ]
