# Generated by Django 4.2.4 on 2023-09-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_rename_user_client_alter_settings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='client',
            field=models.ManyToManyField(to='mailing.client', verbose_name='Получатели'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='period',
            field=models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default=('daily', 'Ежедневно'), max_length=20, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='status',
            field=models.CharField(choices=[('created', 'создана'), ('launched', 'запушена'), ('finished', 'завершена')], default=('created', 'создана'), max_length=20, verbose_name='Статус'),
        ),
    ]
